#!/usr/bin/env python3
"""Builds js/words.js from data/answers-{3,5,7}.txt and the system dictionary.

Answers are the hand-picked daily words for each length. Accepted guesses are
every lowercase word of that length in /usr/share/dict/words (Webster's 2nd,
public domain), plus simple inflections that dictionary leaves out (plurals,
past tenses, -ing forms, comparatives) so guesses like BOOKS, FADED or
PRINTED are accepted.

Run from the project root:  python3 tools/build_words.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DICT = Path("/usr/share/dict/words")
LENGTHS = (3, 5, 7)
VOWELS = set("aeiou")

# Common inflections the rules below can't derive.
EXTRAS = {
    3: [],
    5: """
        being doing dying eying going lying tying vying
        cried dried fried plied pried spied tried
        cries dries flies fries plies pries skies spies tries
        boxes foxes taxes waxes mixes fixes buses gases
        added ended acted asked aimed aided armed owned opted oiled aired erred
        inked axing eking
    """.split(),
    7: [],
}


def plural_ok(word):
    if word[-1] in "sxz" or word.endswith(("sh", "ch")):
        return False
    if word[-1] == "y" and word[-2] not in VOWELS:
        return False
    return True


def cvc(word):
    """Short words like STOP or RUN that double their last letter (STOPPED, RUNNING)."""
    return (len(word) >= 3 and word[-1] not in VOWELS | set("wxy")
            and word[-2] in VOWELS and word[-3] not in VOWELS)


def inflections(by_len, n):
    out = set()
    # one letter longer: plurals, and -d / -r on words ending in e
    for w in by_len.get(n - 1, ()):
        if plural_ok(w):
            out.add(w + "s")
        if w.endswith("e"):
            out.update((w + "d", w + "r"))
    if n == 7:
        for w in by_len[5]:
            if w[-1] == "e":
                out.update((w[:-1] + "ing", w + "ly"))           # writing, bravely
            elif w[-1] == "y" and w[-2] not in VOWELS:
                out.update((w[:-1] + "ied", w[:-1] + "ies"))     # carried, studies
            else:
                out.update((w + "ed", w + "er", w + "ly"))       # printed, printer, quickly
        for w in by_len[4]:
            out.add(w + "ing")                                    # jumping
            if cvc(w):
                out.add(w + w[-1] + "ed")                         # stopped
        for w in by_len[3]:
            if cvc(w):
                out.add(w + w[-1] + "ing")                        # running
    return {w for w in out if len(w) == n}


def main():
    lines = [l.strip() for l in DICT.read_text().splitlines()]
    by_len = {}
    for w in lines:
        if re.fullmatch(r"[a-z]+", w):
            by_len.setdefault(len(w), set()).add(w)

    data = {}
    for n in LENGTHS:
        answers = (ROOT / "data" / f"answers-{n}.txt").read_text().split()
        bad = [w for w in answers if not re.fullmatch(rf"[a-z]{{{n}}}", w)]
        if bad:
            raise SystemExit(f"answers-{n}.txt has words that aren't {n} lowercase letters: {bad}")
        if len(set(answers)) != len(answers):
            raise SystemExit(f"answers-{n}.txt has duplicate words")

        valid = set(by_len.get(n, ())) | inflections(by_len, n) | set(EXTRAS[n]) | set(answers)
        data[n] = {"answers": answers, "guesses": sorted(valid - set(answers))}
        print(f"{n} letters: {len(answers)} answers, {len(data[n]['guesses'])} extra accepted guesses")

    body = ",\n".join(
        f"  {n}: {{\n    answers: {json.dumps(d['answers'], separators=(',', ':'))},\n"
        f"    guesses: {json.dumps(d['guesses'], separators=(',', ':'))}\n  }}"
        for n, d in data.items()
    )
    out = ("// Generated by tools/build_words.py. Edit data/answers-*.txt, then rerun.\n"
           "window.WORDS = {\n" + body + "\n};\n")
    (ROOT / "js" / "words.js").write_text(out)
    print("-> js/words.js")


if __name__ == "__main__":
    main()
